web:
  image: reg.hnzy.com/test/webdemo:master-f2aa0ae
  command: python app.py
  links:
   - redis:redis
lb:
  ports:
  - 80:5000
  image: rancher/load-balancer-service
  links:
  - web:web
redis:
  image: redis
