.catalog:
  name: "WebDemo"
  version: "v0.2"
  description: "WebDemo"
web:
  scale: 2
lb:
  scale: 1
  load_balancer_config:
    haproxy_config: {}
  health_check:
    port: 42
    interval: 2000
    unhealthy_threshold: 3
    healthy_threshold: 2
    response_timeout: 2000
redis:
  scale: 1
