.catalog:
  name: "WebDemo"
  version: "v0.2"
  description: "这是一个基于Python代码的Web应用测试程序"
web:
  scale: 1
lb:
  scale: 1
  load_balancer_config:
    haproxy_config: {}
  health_check:
    port: 42
    interval: 2000
    unhealthy_threshold: 3
    strategy: recreate
    response_timeout: 2000
    healthy_threshold: 2
redis:
  scale: 1
