.catalog:
  name: "web-lb-demo"
  version: "v0.2"
  description: "web_lb_demo"
web:
  scale: 2
lb:
  scale: 1
  load_balancer_config:
    haproxy_config: {}
  health_check:
    port: 42
    interval: 2000
    unhealthy_threshold: 3
    strategy: recreate
    response_timeout: 2000
    healthy_threshold: 2
database:
  scale: 1
